<a href="https://colab.research.google.com/github/pankaj-pixel/Automation-by-Python/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np


#Tensors Dimensions

In [7]:
zero_dim_tensor = tf.constant(4)
print(zero_dim_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
one_dim_array = tf.constant([1,2,3])
print(one_dim_array)
print(one_dim_array.shape)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
(3,)


In [9]:
two_dim_array = tf.constant([
    [2,3,4],
    [5,6,7]
])
print(two_dim_array)


tf.Tensor(
[[2 3 4]
 [5 6 7]], shape=(2, 3), dtype=int32)


In [16]:
three_dim_array =tf.constant([
    [[1,2,3,4],
     [6,7,8,9]],
    [[3,1,3,5],
     [7,8,9,1]],
])
print(three_dim_array)

tf.Tensor(
[[[1 2 3 4]
  [6 7 8 9]]

 [[3 1 3 5]
  [7 8 9 1]]], shape=(2, 2, 4), dtype=int32)


In [17]:
four_D_array =tf.constant([[
    [[1,2,3,4],
     [6,7,8,9]],
    [[5,4,3,2],
     [5,6,8,9]],
]])
print(four_D_array)

tf.Tensor(
[[[[1 2 3 4]
   [6 7 8 9]]

  [[5 4 3 2]
   [5 6 8 9]]]], shape=(1, 2, 2, 4), dtype=int32)


#Printing The Dimensions Of Tensor

In [19]:
print(two_dim_array.ndim)
print(three_dim_array.ndim)

2
3


**converting the tensor data type from float To Integer**

In [30]:
one_d_tensor = tf.constant([1,2,3,4,5],dtype=tf.float16)
print(one_d_tensor)

converting =  tf.cast(one_d_tensor,dtype=tf.int16)
print(converting)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float16)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int16)


In [31]:
string_tensor = tf.constant(["string1","string2","string3"])
print(string_tensor)

tf.Tensor([b'string1' b'string2' b'string3'], shape=(3,), dtype=string)


#**converting numpy array Into Tensor**

In [39]:
array1 =  np.array([1,2,3,4,5])
print(type(array1))

tensor_convert = tf.convert_to_tensor(array1)
print(tensor_convert)
print(type(tensor_convert))

<class 'numpy.ndarray'>
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int64)
<class 'tensorflow.python.framework.ops.EagerTensor'>


#Construct The matrices using tf.eye method

In [47]:
tensor_eye = tf.eye(
    num_rows =3,
    num_columns=5,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(tensor_eye)


tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]], shape=(2, 3, 5), dtype=float32)


**Tensor Fill**

In [57]:
fill = tf.fill([2,3,4],9)
print(fill)

tf.Tensor(
[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]], shape=(2, 3, 4), dtype=int32)


#**Construct Tensor of 1's tf.ones**

In [51]:
ones = tf.ones(shape=[2,3],
               dtype =tf.int32)
print(ones)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [59]:
tf_fill = tf.fill([3,2],8)
print(tf_fill)

tf.Tensor(
[[8 8]
 [8 8]
 [8 8]], shape=(3, 2), dtype=int32)


#tf.ones_like Tensor

In [60]:
one_like = tf.ones_like(tf_fill)
print(one_like)

tf.Tensor(
[[1 1]
 [1 1]
 [1 1]], shape=(3, 2), dtype=int32)


**To Create The Tensor OF zero element tf.zeros**



In [62]:
zero =  tf.zeros([4,5], dtype=tf.int32)
print(zero)

tf.Tensor(
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]], shape=(4, 5), dtype=int32)


#tf.shape = **Returns a tensor containing the shape of the input tenso**r.

In [67]:
shape1 = tf.shape(input=[[2,3],[3,5]])
print(shape1)

tf.Tensor([2 2], shape=(2,), dtype=int32)


In [73]:
t = tf.constant([[[1, 1, 1],
                  [2, 2, 2]],
                  [[3, 3, 3],
                  [4, 4, 4]]])
print(tf.shape(t))

tf.Tensor([2 2 3], shape=(3,), dtype=int32)


**tf.size**

In [72]:
tf_size = tf.constant([[1,2,3],
                       [4,5,6],
                       [8,9,10]])
print(tf_size)
tf.size(tf_size)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]], shape=(3, 3), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=9>

#SORTING THE *TENSORS*

In [3]:
a = [14,3,1.2,4,7.2,1,2.2]
print(tf.sort(a).numpy())
print(tf.sort(a, direction = 'DESCENDING').numpy())

[ 1.   1.2  2.2  3.   4.   7.2 14. ]
[14.   7.2  4.   3.   2.2  1.2  1. ]


#tf.random.normal()

Used to create a random seed for the distribution.





In [11]:
print(tf.random.normal([2,3],mean=10,stddev=1))

tf.Tensor(
[[10.161645  9.303738  9.289399]
 [11.96313   9.268343 10.803902]], shape=(2, 3), dtype=float32)
